### ISSUE TITLE
2.0.0 roadmap

### ISSUE THREAD

**Issue by Joannis** [OpenKitten/MongoKitten#24]
Must:
- [x] Proper SSL Support
- [x] 100% Documentation
- [ ] Make final API breaking changes to clean up the code clarity
- [x] Fix `MongoError` messages for more clarity and context. Especially `CommandFailure`
- [x] Rename QueryProtocol
- [x] Return the amount of updated documents in `update` 

API Changes:
- [x] Different methods for creating Projection Documents
- [x] Increase the amount of places where `limitedBy` and `skipping` can be used
- [x] Simple system for looking up references

Should:
- [ ] Support MongoDB Roles
- [ ] Complete Unit Tests

Could (not sure yet):
- [ ] Simple model system

**Comment by Joannis** [comment]
Any feedback is appreciated

**Comment by Joannis** [comment]
SSL support using an external C7 compliant socket library

**Comment by Joannis** [comment]
@Obbut MongoDB text index helpers? For creating search indexes and searching through databases?
